"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/OqTgwrPwjZb
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card";
import { Product } from "@/lib/schemas/products";

export function OrderConfirmed({ product }: { product: Product }) {
  return (
    <Card className="w-full p-8 flex flex-col items-center justify-center text-center">
      <div className="bg-green-500 rounded-full p-4 mb-4">
        <CheckIcon className="h-8 w-8 text-white" />
      </div>
      <h2 className="text-2xl font-bold mb-2">
        {product.type === "one-off" ? "Order" : "Subscription"} Confirmed
      </h2>
      <p className="text-gray-500 dark:text-gray-400">
        Thank you for{" "}
        {product.type === "one-off" ? "ordering" : "subscribing to"}{" "}
        {product.name}. We're processing it now and will send you a confirmation
        email shortly.
      </p>
    </Card>
  );
}

function CheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  );
}
