"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/VFdYPYy7iUy
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card";
import {
  CarouselItem,
  CarouselContent,
  CarouselPrevious,
  CarouselNext,
  Carousel,
} from "@/components/ui/carousel";
import { useActions, useUIState } from "ai/rsc";
import { Button } from "./ui/button";
import { ClientMessage } from "@/app/actions";
import { nanoid } from "nanoid";
import { Product } from "@/lib/schemas/products";

export function ProductCarousel({ products }: { products: Product[] }) {
  const [_, setConversation] = useUIState();
  const { continueConversation } = useActions();

  return (
    <Carousel className="w-full max-w-2xl">
      <CarouselContent>
        {products.map((p) => (
          <CarouselItem key={p.name}>
            <Card className="flex flex-col items-center gap-4 p-6">
              <div className="text-center">
                <h3 className="text-xl font-semibold">{p.name}</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  {p.description}
                </p>
                <Button
                  className="mt-4"
                  variant="outline"
                  onClick={async () => {
                    setConversation((currentConversation: ClientMessage[]) => [
                      ...currentConversation,
                      {
                        id: nanoid(),
                        role: "user",
                        display: "Get product info for " + p.name,
                      },
                    ]);

                    const message = await continueConversation(
                      "Get product info for " + JSON.stringify({ product: p })
                    );

                    setConversation((currentConversation: ClientMessage[]) => [
                      ...currentConversation,
                      message,
                    ]);
                  }}
                >
                  More info
                </Button>
              </div>
            </Card>
          </CarouselItem>
        ))}
      </CarouselContent>
      <CarouselPrevious />
      <CarouselNext />
    </Carousel>
  );
}
